#library "commands"
#include "zcommon.acs"
#define MAX_VOLUME 127

Script 6003 (VOID) NET
{
	GiveInventory("DoFlameBelch",1);
	GiveInventory("DoShoulderCannon",1);
}

Script 6005 (VOID) NET
{
	GiveInventory("DoIceBomb",1);
	GiveInventory("DoShoulderCannon",1);
}

script "GKEquipmentLauncher" ENTER
{
	int FBCooldown_tic, IBCooldown_tic;
	int FlameBelch_Cooldown, IceBomb_Cooldown;
	int FlameBelch_Ready, IceBomb_Ready;
	
	GiveInventory("FlameBelchReady", 1);
	GiveInventory("IceBombReady", 1);

	while(true) 
	{
		FBCooldown_tic = CheckInventory("CoolFlameBelch");
		IBCooldown_tic = CheckInventory("CoolIceBomb");
		
		FlameBelch_Cooldown = GetCVar("sv_Flamebelch_Cool");
		IceBomb_Cooldown = GetCVar("sv_Icebomb_Cool");
		
		FlameBelch_Ready = CheckInventory("FlameBelchReady");
		IceBomb_Ready = CheckInventory("IceBombReady");
		
		if(FBCooldown_tic < FlameBelch_Cooldown && FlameBelch_Ready != 1)
		{
			GiveInventory("CoolFlameBelch",1);
		}
		if(IBCooldown_tic < IceBomb_Cooldown && IceBomb_Ready != 1)
		{
			GiveInventory("CoolIceBomb",1);
		}
		
		if(FBCooldown_tic == FlameBelch_Cooldown)
		{
			TakeInventory("CoolFlameBelch", FlameBelch_Cooldown);
			GiveInventory("FlameBelchReady", 1);
			LocalAmbientSound("Equip_flameready", MAX_VOLUME);
		}
		if(IBCooldown_tic == IceBomb_Cooldown)
		{
			TakeInventory("CoolIceBomb", IceBomb_Cooldown);
			GiveInventory("IceBombReady", 1);
			LocalAmbientSound("Equip_Iceready", MAX_VOLUME);
		}
		Delay(35);
	}
	Delay(35);
}