#library "lowhealth.acs"
#include "zcommon.acs"

#define MAX_VOLUME 127


//lowhealth scripts - from BoA
script "lowhealth" ENTER
{
	bool LowHP;

	while(true)
	{
		if (!GetCVar("be_LowHealthAlert"))
		{
			LowHP = false;
			Delay(1);
			continue;
		}

		int health = GetActorProperty(0, APROP_HEALTH);

		if (health <= GetCVar("sv_LowHealthValue"))
		{
			if (!LowHP)
			{
				LocalAmbientSound("LOWHEALTH", MAX_VOLUME);
				LowHP = true;
			}
		}
		else
		{
			LowHP = false;
		}
		Delay(1);
	}
}

script "lowarmor" ENTER
{
	bool LowArmor;
	bool ArmorEquip;

	while(true)
	{
		if (!GetCVar("be_LowArmorAlert"))
		{
			LowArmor = false;
			ArmorEquip = false;
			Delay(1);
			continue;
		}

		int Armor = CheckInventory("BasicArmor");
		if (Armor > GetCVar("sv_LowArmorValue"))
		{
			ArmorEquip = true;
		}
		
		if (Armor <= GetCVar("sv_LowArmorValue"))
		{
			if (!LowArmor && ArmorEquip)
			{
				LocalAmbientSound("LOWARMOR", MAX_VOLUME);
				LowArmor = true;
				ArmorEquip = false;
			}
		}
		else
		{
			LowArmor = false;
		}
		Delay(1);
	}
}